sudo: required
language: generic

services:
    - docker

branches:
  except:
    - /^debian\/\d/

script:
    - wget -O- https://raw.githubusercontent.com/harisvsulaiman/element-build/master/script.sh | sh -

after_success:
    - bash -ex data/appimage.sh || true

deploy:
  skip_cleanup: true


