name: meteo
version: '0.6.1'
summary: Know the forecast of the next hours and days, with data and maps
description: |
    Current weather, with information about temperature, pressure, wind
    speed and direction, sunrise and sunset. Show awesome maps with all
    this information. Switch between some maps distributors.
grade: devel
confinement: devmode

icon: data/com.github.bitseater.weather.svg

apps:
  meteo:
    command: bin/snapcraft-preload $SNAP/usr/bin/com.github.bitseater.weather
    plugs:
        - x11
        - desktop
        - desktop-legacy
        - wayland
        - unity7
        - home
        - browser-support
        - locale-control
        - gsettings
        - network
        - opengl
    desktop: usr/share/applications/com.github.bitseater.weather.desktop
    environment:
        GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
        LD_LIBRARY_PATH: $SNAP/usr/lib/*/webkit2gtk-4.0/:$LD_LIBRARY_PATH

parts:
    meteo:
        after: [desktop-gtk3, snapcraft-preload]
        source: https://github.com/bitseater/weather.git
        source-type: git
        plugin: meson
        meson-parameters: [--prefix=/usr]
        prepare: |
             pip3 install meson
        build-packages:
            - desktop-file-utils
            - python3-pip
            - build-essential
            - gettext
            - libgee-0.8-dev
            - valac
            - libjson-glib-dev
            - meson
            - ninja-build
            - debhelper
            - libsoup2.4-dev
            - libgeocode-glib-dev
            - libclutter-1.0-dev
            - libclutter-gtk-1.0-dev
            - libchamplain-0.12-dev
            - libwebkit2gtk-4.0-dev
            - libappindicator3-dev
        stage-packages:
            - locales-all
            - libgdk-pixbuf2.0-0
            - libclutter-1.0-0
            - libclutter-gtk-1.0-0
            - libchamplain-0.12-0
            - libgeocode-glib0
            - libwebkit2gtk-4.0-37
            - libappindicator3-1
            - libcanberra-gtk3-module
        install: |
            glib-compile-schemas $SNAP/usr/share/glib-2.0/schemas
