name: meteo
version: '0.6.1'
summary: Know the forecast of the next hours and days, with data and maps
description: |
    Current weather, with information about temperature, pressure, wind
    speed and direction, sunrise and sunset. Show awesome maps with all
    this information. Switch between some maps distributors.
grade: devel
confinement: devmode

icon: data/com.github.bitseater.weather.svg

plugs:
    elementary-platform-loki:
        interface: content
        target: $SNAP/gnome-platform
        default-provider: elementary-platform-loki:elementary-platform-loki

apps:
  meteo:
    command: desktop-launch snapcraft-preload $SNAP/usr/bin/com.github.bitseater.weather
    plugs:
        - x11
        - desktop
        - desktop-legacy
        - wayland
        - unity7
        - home
        - browser-support
        - locale-control
        - gsettings
        - network
        - opengl
    desktop: usr/share/applications/com.github.bitseater.weather.desktop
    environment:
        GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
        LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/:$LD_LIBRARY_PATH

parts:
    meteo:
        after: [desktop-gtk3, snapcraft-preload]
        source: https://github.com/bitseater/weather.git
        source-type: git
        plugin: meson
        meson-parameters: [--prefix=/usr]
        build-packages:
            - build-essential
            - gettext
            - libgee-0.8-dev
            - valac
            - libjson-glib-dev
            - meson
            - ninja-build
            - debhelper
            - libsoup2.4-dev
            - libgeocode-glib-dev
            - libclutter-1.0-dev
            - libclutter-gtk-1.0-dev
            - libchamplain-0.12-dev
            - libwebkit2gtk-4.0-dev
            - libappindicator3-dev
        stage-packages:
            - locales-all
            - libgdk-pixbuf2.0-0
            - libclutter-1.0-0
            - libclutter-gtk-1.0-0
            - libchamplain-0.12-0
            - libgeocode-glib0
            - libwebkit2gtk-4.0-37
            - libappindicator3-1
            - libcanberra-gtk3-module
        filesets:
            exclude:
                - -lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2
                - -usr/lib/x86_64-linux-gnu/glib-2.0/gio-querymodules
                - -usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-resources
                - -usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas
                - -usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.4800.2
                - -usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4800.2
                - -usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.2
                - -usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.2
                - -usr/share/doc/hicolor-icon-theme/NEWS.gz
                - -usr/share/doc/hicolor-icon-theme/changelog.Debian.gz
                - -usr/share/doc/libglib2.0-0/changelog.Debian.gz
                - -usr/share/icons/hicolor/index.theme
        stage:
            - $exclude


