name: meteo
version: '0.6.1'
summary: Know the forecast of the next hours and days, with data and maps
description: |
  Current weather, with information about temperature, pressure, wind
  speed and direction, sunrise and sunset. Show awesome maps with all
  this information. Switch between some maps distributors.
grade: devel
confinement: devmode

icon: data/com.github.bitseater.weather.svg

plugs:
  elementary-platform-loki:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: elementary-platform-loki:elementary-platform-loki

apps:
  meteo:
    command: bin/desktop-launch $SNAP/usr/bin/com.github.bitseater.weather
    plugs:
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - browser-support
      - locale-control
      - gsettings
      - network
      - opengl
    desktop: usr/share/applications/com.github.bitseater.weather.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $SNAP/usr/lib/*/webkit2gtk-4.0/:$LD_LIBRARY_PATH

parts:
  granite:
    plugin: cmake
    source: https://github.com/elementary/granite/archive/0.5.tar.gz
    source-type: tar
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_INSTALL_LIBDIR=/usr/lib]
    build-packages:
      - build-essential
      - valac
    stage-packages:
      - valac-0.30-vapi
  elementary:
    plugin: nil
    prepare: |
      apt install -y --allow-downgrades software-properties-common
      add-apt-repository -y ppa:elementary-os/stable
      add-apt-repository -y ppa:elementary-os/os-patches
      echo "Package: *" > /etc/apt/preferences.d/elementary-stable
      echo "Pin: release o=LP-PPA-elementary-os-stable" >> /etc/apt/preferences.d/elementary-stable
      echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-stable
      echo "Package: *" > /etc/apt/preferences.d/elementary-patches
      echo "Pin: release o=LP-PPA-elementary-os-os-patches" >> /etc/apt/preferences.d/elementary-patches
      echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-patches
      apt update
      apt dist-upgrade -y
  meteo:
    after: [granite, elementary, desktop-gtk3]
    source: https://github.com/bitseater/weather.git
    source-type: git
    plugin: meson
    meson-parameters: [--prefix=/usr]
    prepare: |
      apt-get install -y python3-setuptools
      pip3 install meson
    build-packages:
      - desktop-file-utils
      - python3-pip
      - build-essential
      - gettext
      - libgee-0.8-dev
      - valac
      - libjson-glib-dev
      - meson
      - ninja-build
      - debhelper
      - libsoup2.4-dev
      - libgeocode-glib-dev
      - libclutter-1.0-dev
      - libclutter-gtk-1.0-dev
      - libchamplain-0.12-dev
      - libwebkit2gtk-4.0-dev
      - libappindicator3-dev
    stage-packages:
      - locales-all
      - libgdk-pixbuf2.0-0
      - libclutter-1.0-0
      - libclutter-gtk-1.0-0
      - libchamplain-0.12-0
      - libgeocode-glib0
      - libwebkit2gtk-4.0-37
      - libappindicator3-1
      - libcanberra-gtk3-module
    install: |
      glib-compile-schemas $SNAP/usr/share/glib-2.0/schemas
