name: meteo
version: '0.6.0'
summary: Know the forecast of the next hours and days with data and maps
description:
    Current weather, with information about temperature, pressure, wind
    speed and direction, sunrise and sunset. Show awesome maps with all
    the information. Switch between some maps distributors.
icon: data/com.github.bitseater.weather.svg
grade: devel
confinement: devmode

plugs:
    elementary-platform-loki:
        interface: content
        target: $SNAP/gnome-platform
        default-provider: elementary-platform-loki:elementary-platform-loki

apps:
  meteo:
    command: desktop-launch $SNAP/usr/bin/com.github.bitseater.weather
    desktop: usr/share/applications/com.github.bitseater.weather.desktop
    plugs:
        - x11
        - desktop
        - desktop-legacy
        - wayland
        - unity7
        - home
        - gsettings
        - network
    environment:
        LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/:$LD_LIBRARY_PATH

parts:
    granite:
        plugin: cmake
        source: lp:granite/0.5
        source-type: bzr
        configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_INSTALL_LIBDIR=/usr/lib]
        build-packages:
            - build-essential
            - valac
        stage-packages:
            - valac-0.30-vapi

    elementary:
        plugin: nil
        prepare: |
            sudo add-apt-repository -y ppa:elementary-os/stable
            sudo add-apt-repository -y ppa:elementary-os/os-patches
            echo "Package: *" > sudo /etc/apt/preferences.d/elementary-stable
            echo "Pin: release o=LP-PPA-elementary-os-stable" >> sudo /etc/apt/preferences.d/elementary-stable
            echo "Pin-Priority: 1000" >> sudo /etc/apt/preferences.d/elementary-stable
            echo "Package: *" > sudo /etc/apt/preferences.d/elementary-patches
            echo "Pin: release o=LP-PPA-elementary-os-os-patches" >> sudo /etc/apt/preferences.d/elementary-patches
            echo "Pin-Priority: 1000" >> sudo /etc/apt/preferences.d/elementary-patches
            sudo apt update
            sudo apt dist-upgrade -y

    meteo:
        after: [granite, elementary, desktop-gtk3]
        source: https://github.com/bitseater/weather.git
        plugin: meson
        meson-parameters: [--prefix=/usr]
        build-packages:
            - appstream
            - desktop-file-utils
            - gettext
            - build-essential
            - valac
            - meson
            - ninja-build
            - intltool
            - libgee-0.8-dev
            - debhelper
            - libgtk-3-dev
            - libgranite-dev
            - libwebkit2gtk-4.0-dev
            - libsoup2.4-dev
            - libjson-glib-dev
            - libgeocode-glib-dev
            - libclutter-1.0-dev
            - libclutter-gtk-1.0-dev
            - libchamplain-0.12-dev
        install: |
            cp data/com.github.bitseater.weather.gschema.xml $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
            glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
        prime:
            - usr/share
        organize:
            share/glib-2.0: usr/share/glib-2.0

